#!/bin/bash

: ${JAVA:=/usr/bin/java}
: ${PILLAR_ROOT:=/opt/pillar}

export PILLAR_ROOT

CLASS=com.chrisomeara.pillar.cli.App
CLASS_PATH=${PILLAR_ROOT}/lib/pillar.jar:${PILLAR_ROOT}/conf

$JAVA -cp $CLASS_PATH $JAVA_OPTS $CLASS $*
